### ISSUE TITLE
Changing the cxl-playbook-progress-bar DOM location results in error

### ISSUE THREAD

**Issue by dominik-stypula-polcode** [conversionxl/aybolit#164] opened 2021-07-19 15:12 UTC
![issue-progress-bar](https://user-images.githubusercontent.com/54673942/126177319-05c76875-4637-4a47-ae68-7c63c48b7983.png)

Error is caused by using `this.closest()` instead of `document.querySelector()`:
https://github.com/conversionxl/aybolit/blob/3760a0ccbe7c1886cdbc8a4c4e70e3df00172654/packages/cxl-ui/src/components/cxl-playbook-progress-bar.js#L38

@lkraav @saas786 what was the idea behind this limitation? 
Seems it is easy fixable by changing to:
`this._listenOnClosestElement = document.querySelector(this.listenOnClosest);` - of course in that case variable naming should also be refactored.

**Reproducing the error**
Change the location of the component to the sidebar like follows:
```
      <section class="widget ${hasWidgetBackground ? 'has-background' : ''}" slot="sidebar">
        <p>
          <label for="cxl-playbook-progress-bar-${playbookId}"></label>
          <cxl-playbook-progress-bar
            id="cxl-playbook-progress-bar-${playbookId}"
          ></cxl-playbook-progress-bar>
          <!-- [listen-on-closest] fixes race condition vs article classes computation -->
        </p>
      </section>
```

**Comment by lkraav** [comment] 2021-07-19 18:08
This element was designed to operate in a very specific context. I'm not currently convinced we should be moving progress bar out of sidebar, mainly because if we want to make it a sticky element soon enough (integrate with upcoming Action Bar maybe), it might be adding additional complexity.

We should probably revisit this after Action Bar lands.

**Comment by heshfekry** [comment] 2021-07-19 18:16
@lkraav that makes sense. 

However we need to move some items like author underneath the playbook title. As well as have the Peer reviewer links there as well. 

I recommend hiding the progress bar for now till action bar is deployed and this issue is revisited. The number of tick box interactions is super low, and it doesn't make justify bottle necking other iterative UI updates by eating up half the screen.

I will write up those issues and log them in the [CXL ui build list](https://app.clickup.com/2317190/v/l/5-31845376-1)

**Comment by heshfekry** [comment] 2021-07-19 19:07
[Closing issue for now due. can re-open if necessecary](https://github.com/conversionxl/aybolit/issues/164#issuecomment-882757824)

**Closed by heshfekry** 2021-07-19 19:07 UTC
